### ISSUE TITLE
Hi, what's the prompt for NER task?

### ISSUE THREAD

**Issue by wmkai** [4AI/LS-LLaMA#18]

**Comment by SeanLee97** [comment]
@wmkai do you mean the prompt for the zero-shot NER setting?

**Comment by wmkai** [comment]
hmm, I want the prompt for the result of NER in CONLL2003. Does it have a prompt?
<img width="576" alt="image" src="https://github.com/4AI/LS-LLaMA/assets/39148461/a120d558-5899-4fa5-8e5b-968a7ede8bf7">

**Comment by SeanLee97** [comment]
hi @wmkai, it is **unnecessary** to set a prompt for LS-unLLaMA since the generation ability will malfunction when transforming all layers into bidirectional.

BTW, it's recommended to use the `BiLLM` toolkit to train NER. Here is a training and inference example:

https://github.com/WhereIsAI/BiLLM?tab=readme-ov-file#ner

**Comment by SeanLee97** [comment]
Here are two pretrained models for the conll2003 dataset:

- mistral-7b: https://huggingface.co/WhereIsAI/billm-mistral-7b-conll03-ner
- llama-7b: https://huggingface.co/WhereIsAI/billm-llama-7b-conll03-ner

**Comment by wmkai** [comment]
I see. Thank u very much :)
